name: Allocate definitive IDs

on:
  push:
    branches: [ master ]
    paths:
      - 'src/ontology/uberon-edit.obo'
  workflow_dispatch:

jobs:
  assign_ids:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Allocate definitive IDs
        run: |
          cd src/ontology
          make allocate-definitive-ids

      - name: Commit and push changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Replace temporary IDs by definitive IDs."
          branch: ${{ github.ref }}
