name: Check for modified inferences

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - 'src/**'

jobs:

  check_inferences:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6
    outputs:
      n_impacted_classes: ${{ steps.collect_results.outputs.INFER_DIFF_N }}
      max_removed_classes: ${{ steps.collect_results.outputs.INFER_MAX_REMOVED }}
      max_added_classes: ${{ steps.collect_results.outputs.INFER_MAX_ADDED }}
    steps:
      - name: checkout the head of the PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: checkout the base of the PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: Enable ROBOT Uberon plugin
        working-directory: base/src/ontology
        run: |
          make all_robot_plugins
          echo "ROBOT_PLUGINS_DIRECTORY=base/src/ontology/tmp/plugins/" >> "$GITHUB_ENV"
      - name: Run the inference diff report
        run: |
          robot uberon:inference-diff --input head/src/ontology/uberon-edit.obo \
                                      --catalog head/src/ontology/catalog-v001.xml \
                                      --base-file base/src/ontology/uberon-edit.obo \
                                      --base-catalog base/src/ontology/catalog-v001.xml \
                                      --base-iri http://purl.obolibrary.org/obo/UBERON_
      - name: Collect numeric results
        id: collect_results
        run: |
          sed -nre 's/^Number of classes with modified logical definitions: /INFER_DIFF_N=/p' inference-diff.md >> $GITHUB_OUTPUT
          echo "Removed subclasses: 0" > dummy.md
          echo "Added subclasses: 0" >> dummy.md
          cat inference-diff.md dummy.md | \
            sed -nre 's/^Removed subclasses: /INFER_MAX_REMOVED=/p' | \
            sort -k2 -t= -n -r | head -n 1 >> $GITHUB_OUTPUT
          cat inference-diff.md dummy.md | \
            sed -nre 's/^Added subclasses: /INFER_MAX_ADDED=/p' | \
            sort -k2 -t= -n -r | head -n 1 >> $GITHUB_OUTPUT
      - name: Prepare comment
        if: steps.collect_results.outputs.INFER_DIFF_N > 0
        run: |
          echo "<details>\nThis PR modifies some logical definitions.</summary>\n" > comment.md
          cat inference-diff.md >> comment.md
      - name: Post comment
        if: steps.collect_results.outputs.INFER_DIFF_N > 0
        uses: NejcZdovc/comment-pr@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: "../../comment.md"
          identifier: "INFERENCE_DIFF"
